<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>S</string>
	</array>
	<key>name</key>
	<string>WinDlx (by MaciejLisCK)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment eg. ;some comment</string>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\.data)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>data section</string>
			<key>end</key>
			<string>(?=\.text)</string>
			<key>name</key>
			<string>meta.data</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Comment eg. ;some comment</string>
					<key>match</key>
					<string>;.*</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*([A-Za-z_][A-Za-z0-9_]*)(\:)</string>
					<key>name</key>
					<string>meta.data.variable.name</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>data definition</string>
					<key>match</key>
					<string>\.(byte|word|float|double|asciiz|space)</string>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>constant</string>
					<key>match</key>
					<string>\d+.?\d*</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>text</string>
					<key>match</key>
					<string>\"[^\"]*\"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\.text)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text section</string>
			<key>end</key>
			<string>(?=\.data)</string>
			<key>name</key>
			<string>meta.text</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Comment eg. ;some comment</string>
					<key>match</key>
					<string>;.*</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>label</string>
					<key>match</key>
					<string>^\s*([A-Za-z_][A-Za-z0-9_]*\:)</string>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>instruction eg. sgei r30, r1,</string>
					<key>match</key>
					<string>^\s*(?i)(__d|__f|add|addd|addf|addi|addu|addui|and|andi|beqz|bfpf|bfpt|bnez|cvtd2f|cvtd2i|cvtf2d|cvtf2i|cvti2d|cvti2f|div|divd|divf|divu|eqd|eqf|fparith|ged|gef|gtd|gtf|j|jal|jalr|jr|la|lb|lbu|ld|led|lef|lf|lh|lhi|lhu|ltd|ltf|lw|movd|movf|movfp2i|movi2fp|movi2s|movs2i|mult|multd|multf|multu|ned|nef|nop|or|ori|rfe|s__|s__i|sb|sd|seq|seqi|sf|sge|sgei|sgeu|sgeui|sgt|sgti|sgtu|sgtui|sh|sle|slei|sleu|sleui|sll|slli|slt|slti|sltu|sltui|sne|snei|special|sra|srai|srl|srli|sub|subd|subf|subi|subu|subui|sw|trap|xor|xori)\s+</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>registers eg. f0</string>
					<key>match</key>
					<string>\b(?i)(pc|imar|ir|a|ahi|b|bhi|bta|alu|aluhi|fpsr|dmar|sdr|sdrhi|ldr|ldrhi|r0|r1|r2|r3|r4|r5|r6|r7|r8|r9|r10|r11|r12|r13|r14|r15|r16|r17|r18|r19|r20|r21|r22|r23|r24|r25|r26|r27|r28|r29|r30|r31|f0|f1|f2|f3|f4|f5|f6|f7|f8|f9|f10|f11|f12|f13|f14|f15|f16|f17|f18|f19|f20|f21|f22|f23|f24|f25|f26|f27|f28|f29|f30|f31|d0|d2|d4|d6|d8|d10|d12|d14|d16|d18|d20|d22|d24|d26|d28|d30)\b</string>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>operator</string>
					<key>match</key>
					<string>(|\+|\-)</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>constant</string>
					<key>match</key>
					<string>\#\d+\.?\d*</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>constant</string>
					<key>match</key>
					<string>\b\d+\.?\d*\b</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>label</string>
					<key>match</key>
					<string>^\s*(\.[A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([A-Za-z_][A-Za-z0-9_]*\()\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>table</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>variable names</string>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z_0-9]*\b</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.windlx</string>
	<key>uuid</key>
	<string>812c3098-70a7-45ce-9a27-198918953507</string>
</dict>
</plist>
